Moved current tick incrementation outside of the if-initialized block
0xKitsune/cfmms-rs pull request #91
Opened 2023-05-16 19:37 UTC by da-bao-jian

for fn simulate_swap_mut_with_cache and fn simulate_swap_with_cache, the original implementation in [UniswapV3Pool.sol](https://github.com/Uniswap/v3-core/blob/d8b1c635c275d2a9450bd6a78f3fa2484fef73eb/contracts/UniswapV3Pool.sol#L725) will move the current tick no matter if the tick is initialized or not.

2023-05-22 19:31 UTC, 0xOsiris requested changes
LGTM, just added a few comments. Can you also run `cargo fmt` and `cargo clippy --fix` so ci passes.

2023-05-22 19:31 UTC, 0xOsiris commented on src/pool/mod.rs
> +#[derive(Clone, Copy, Debug, PartialEq, Eq)]
Can you remove `PartialEq` & `Eq` traits. Imo these wouldn't have much utility in this context?

2023-05-22 19:31 UTC, 0xOsiris commented on src/pool/uniswap_v2.rs
> +#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
Can you remove `PartialEq` & `Eq` here as well

2023-05-22 19:31 UTC, 0xOsiris commented on src/pool/uniswap_v3.rs
> +#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
Here as well

2023-05-25 02:20 UTC, 0xKitsune commented
Thanks for making this PR! Once the requested changes are addressed, we can merge this in.

2023-06-19 02:54 UTC, merged